spring:
  jackson:
    deserialization:
      accept-float-as-int: false
  application:
    name: canton-dex
  sql:
    init:
      mode: always
      schema-locations: classpath:db/V1__schema.sql
  datasource:
    hikari:
      maximum-pool-size: 8
  threads:
    virtual:
      enabled: true
management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      probes:
        enabled: true
      group:
        readiness:
          include: readinessState,db,canton
server:
  shutdown: graceful
